### PR TITLE
Android Device Responsiveness QA - Fix Login, Registration and Step By Step Screens

### LINKED ISSUE #71: Android Device Responsiveness QA
A lot of the UI thus far was designed using a Pixel_3a_API_29 emulator. The design looks perfect on this device. This ticket is to go through some other Android device emulators to ensure the design is still fine on those devices. 

AC
- Refactor any unresponsive UI elements

Note
- Do not spend too long on this task

### PR DESCRIPTION
**Pull request by fcpranav**
Corresponding Issue: #71 

Issues:
- Setting height was the issue, we should use flex for larger containers wherever possible

Tested:
- Tested on S7 (smaller screen than the Pixel)

Screenshots:
image
image
image
image
image
image

Time Spent:
2 hours

### CODE REVIEW

File: PlateUp-reactnative/screens/RecipeStepByStep.js [hunk 1]
```diff
@@ -154,8 +154,10 @@ class RecipeStepByStep extends React.Component {
     });
 
     return (
-      imgs.map((image) => (
-        <Block style={{ marginBottom: 50 }}>
+      imgs.map((image, index) => (
+        // Reasonable to disable here as this is a static array
+        // eslint-disable-next-line react/no-array-index-key
+        <Block key={index} style={{ marginBottom: 50 }}>
```
Comment (fcpranav) [inline PlateUp-reactnative/screens/RecipeStepByStep.js:160]: I sneaked this in as there was a warning constantly showing up on this page.

File: PlateUp-reactnative/screens/Register.js [hunk 2]
```diff
@@ -83,19 +83,19 @@ class Register extends React.Component {
...
-              <KeyboardAvoidingView
-                style={{ flex: 1 }}
-                behavior="padding"
-                enabled
-              >
+        <KeyboardAvoidingView
+          style={{ flex: 1 }}
+          behavior="padding"
+          enabled
+        >
```
Comment (fcpranav) [inline PlateUp-reactnative/screens/Register.js:90]: Moved this view to wrap the container itself. The idea is that the KeyBoardAvoidingView spans the entire phone screen through flex. The register content which we don't want to be flex is centered in the middle of this div.

File: PlateUp-reactnative/screens/Register.js [hunk 3]
```diff
@@ -173,14 +173,12 @@ class Register extends React.Component {
                     Privacy Policy
                   </Text>
                 </Block>
-                {userSettings.status === REGISTER_IPR
-                  ? (
-                    <Block style={styles.loading}>
+                <Block middle style={styles.footer}>
+                  {userSettings.status === REGISTER_IPR
+                    ? (
```
Comment (fcpranav) [inline PlateUp-reactnative/screens/Register.js:178]: Code clean up. Forcing the same styling also ensures the general container size remains the same when the button becomes a loading indicator.

File: PlateUp-reactnative/screens/Login.js [hunk 4]
```diff
@@ -81,19 +81,19 @@ class Login extends React.Component {
...
-                Welcome back to Plate Up! Please log in.
-              </Text>
-            </Block>
-            <Block flex center>
-              <KeyboardAvoidingView
-                style={{ flex: 1 }}
-                behavior="padding"
-                enabled
-              >
+        <KeyboardAvoidingView
```
Comment (fcpranav) [inline PlateUp-reactnative/screens/Login.js:84]: Moved this view to wrap the container itself. The idea is that the KeyBoardAvoidingView spans the entire phone screen through flex. The login content which we don't want to be flex is centered in the middle of this div.

File: PlateUp-reactnative/screens/Login.js [hunk 5]
```diff
@@ -130,14 +130,12 @@ class Login extends React.Component {
                     onChangeText={(password) => this.setState({ password })}
                   />
                 </Block>
-                {userSettings.status === LOGIN_IPR
-                  ? (
-                    <Block style={styles.loading}>
```
Comment (eanile) [inline PlateUp-reactnative/screens/Login.js:135]: Doesn't removing this mess with where the loading indicator is located?

File: PlateUp-reactnative/screens/Register.js (hunk 3 above)
Comment (eanile) [reply PlateUp-reactnative/screens/Register.js:178]: And it doesn't mess with the location of the loading indicator?

File: PlateUp-reactnative/screens/Login.js (hunk 5 above)
Comment (fcpranav) [reply PlateUp-reactnative/screens/Login.js:135]: No because the styling applied is basically equivalent to `middle` prop.

File: PlateUp-reactnative/screens/Register.js (hunk 3 above)
Comment (fcpranav) [reply PlateUp-reactnative/screens/Register.js:178]: No because the styling applied is basically equivalent to middle prop.

**Review by eanile — APPROVED** [review]
